# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
from django.utils.text import slugify

def create_slug(apps, schema_editor):
    Blog = apps.get_model("blog", "Blog")
    for blog in Blog.objects.all():
        blog.slug = slugify(blog.title)
        blog.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161122_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(create_slug),
    ]
