# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 09:38
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

fixture = 'exampleblogs'

def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='blog')

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161124_0231'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
